name: GitHub Dolphin Contributions Visualization
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Generate GitHub Contributions Ocean Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-dolphin.svg
            dist/github-dolphin-dark.svg?palette=github-dark
            dist/ocean-splash.gif?color_snake=blue&color_dots=#87CEEB,#4682B4,#1E90FF,#4169E1,#0000CD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update ocean-themed contributions visualization [skip ci]"
